name: audit
on: [push]
permissions: {}
jobs:
  audit:
    runs-on: macos-14
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install specific npm version
        run: npm install -g npm@11.4.2
      - uses: actions/checkout@v4
      - name: Audit
        run: |
          npm ci --audit false --fund false
          npm audit
